language: node
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_bcf61386e573_key -iv $encrypted_bcf61386e573_iv -in travis-key.json.enc -out travis-key.json -d
  - cat travis-key.json | docker login -u _json_key --password-stdin https://gcr.io
  - rm travis-key.json
install:
  - npm install
  - npm run-script build
  - docker build . -t $IMAGENAME
  - docker tag $IMAGENAME $REGISTRY/$IMAGENAME
  - docker push $REGISTRY/$IMAGENAME
script:
  - echo "done"
