name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: |
          yarn install --frozen-lockfile;
          yarn build;
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: bromberglab/bio-node-webclient
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
